language: go

go:
  - "1.14"

services:
  - docker  

env:
  global:
    - SLACK_TOKEN="test_token"
    - K8S_CLUSTER_NAME="test_cluster"
    - SLACK_CHANNEL_NAMES="my_channel"
    - PORT="8080"
    - GO111MODULE=on

stages:
- unit-tests  
- name: deploy
  if: branch = master

jobs:
  fast_finish: true
  allow_failures:
    - go: master
  include:
    # trigger unit tests    
    - stage: unit-tests
      script:
        - make test

    # deploy docket image to global repository
    - stage: deploy&release
      before_script:
        - source ci/before_script.sh
      script:
        - source ci/release.sh
        

