language: go

go:
  - "1.14"

env:
  global:
    - secure: P06J1GwGcCXqp2dYS4iwqoUOUoa8co/DzcNyzeJnwJL6+68md5sXQ8NJNa9+YN5yNO1c5STKuJ8DUOPw03JljUzPHJkK0TcEsNbUGjiyiP/F6sAR7HdmY0UIU7nxm9MZXim8h/qz3F8Yr0E9zL6EGKkZjTcuxiXwEWbwYPQzTwfSeTKmBp3vijm6EWRDj8k734lNY55O50nqbRcrlkUBrDRqyTFbVjyWTT8cMDD9AHAEJB3Z3KnVjqpdAVxRybr7lre181BryNattqwVAtO1/f5upIs9wTbVX/pqPz7CXb6D9krjMQqxX5Tyh/ErgTmxWAQCt9HHtAQdU54AzEBa2PJlZCP+SOwp5dDhC6NXtyUV+zFgbtlS2l5kT2WWmxKjCi4vjxwyQNVA9HMvmLf4zt1dEBj7t/dyAWqs/Le/085TxL517jCzfE7iCysyKdNH95Hrpd2rwKxtHR7odmA0xwcFIyCfhugVR7xYvPrLMViNLkVyAiCkKYKf+jvFzD0U5K1ZPy5T3ttH+H+TO1TOoGSxUNITNFTnLyXpUhZWCymKJ8z/OodMAX+nrBmBYI7mIHpEfz33KEbqbOamSTJ4D+EpKL+TLekApKE8cvmKlNqe9nPLt13W2AFhi2JgTOruOSsDxmF+Dr0LknCnjBnAlY+HmW0KQ45UJZnjp83Ewvw=

jobs:
  fast_finish: true
  allow_failures:
    - go: master
  include:
    - stage: test
      before_script:
        - mkdir /home/travis/.kube
        - touch /home/travis/.kube/config
      script:
        - go test ./... -v
      env:
        - K8S_CLUSTER_NAME="eks-dev"
        - SLACK_CHANNEL_NAMES="G015JRLJ334"
        - GO111MODULE=on
        - LOG_LEVEL="debug"