language: go

go:
  - "1.14"

services:
  - docker  

env:
  global:
    - SLACK_TOKEN="test_token"
    - K8S_CLUSTER_NAME="test_cluster"
    - SLACK_CHANNEL_NAMES="my_channel"
    - PORT="8080"
    - GO111MODULE=on

stages:
- unit-tests

jobs:
  fast_finish: true
  allow_failures:
    - go: master
  include:
    # trigger unit tests
    - stage: unit-tests
      script:
        - make test
      after_script:
        - go tool cover -func=c.out --exit-code $TRAVIS_TEST_RESULT
