language: go

go:
  - "1.14"

services:
  - docker  

env:
  global:
    - SLACK_TOKEN="test_token"
    - K8S_CLUSTER_NAME="test_cluster"
    - SLACK_CHANNEL_NAMES="my_channel"
    - PORT="8080"
    - GO111MODULE=on

stages:
- unit-tests  
- deploy
  if: branch = master AND type = push AND fork = false  

jobs:
  fast_finish: true
  allow_failures:
    - go: master
  include:
    # trigger unit tests    
    - stage: unit-tests
      script:
        - make test

    # deploy docket image to global repository
    - stage: deploy
      before_script:
        - source ci/before_script.sh
      script:
        - make docker-build-and-push
      after_success:
        - git config user.email "travis@travis.org"
        - git config user.name "travis" # this email and name can be set anything you like
        - ./ci/version-control.sh ${RELEASE_TYPE}
        - git add .
        - git commit -m "Release new version [skip ci]"
        - git push https://shyimo:${GITHUB_API_KEY}@github.com/PayU/kubeobserver.git HEAD:master
      
