language: go

go:
  - "1.14"

install:
  - go get -v github.com/golang/dep/cmd/dep
  - go get -v github.com/codeclimate/test-reporter
  - cd $GOPATH/src/github.com/golang/dep/cmd/dep && git checkout tags/v0.4.1 && go install
  - cd $GOPATH/src/github.com/codeclimate/test-reporter && git checkout tags/v0.4.3 && go install
  - cd - && dep ensure -v -vendor-only

services:
  - docker  

env:
  global:
    - SLACK_TOKEN="test_token"
    - K8S_CLUSTER_NAME="test_cluster"
    - SLACK_CHANNEL_NAMES="my_channel"
    - PORT="8080"
    - GO111MODULE=on

stages:
- unit-tests

jobs:
  fast_finish: true
  allow_failures:
    - go: master
  include:
    # trigger unit tests
    - stage: unit-tests
      before_script:
        - test-reporter before-build
      script:
        - make test
      after_script:
        - test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
